version: 2

build:
  image: latest
  tools:
    python: "3.12"
  apt_packages:
    - dotnet-sdk-6.0

sphinx:
  configuration: docs/conf.py

python:
   install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
