name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.pyver }} on ${{ matrix.platform.os }} ${{ matrix.platform.arch }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        pyver: [cp39, cp310, cp311, cp312]
        platform:
        - arch: x86_64
          os: ubuntu-20.04
        - arch: arm64
          os: macos-11
        - arch: x86_64
          os: macos-11
        - arch: x86
          os: windows-2019
        - arch: AMD64
          os: windows-2019

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2
      env:
        CIBW_BUILD: ${{ matrix.pyver }}-*
        CIBW_ARCHS: ${{ matrix.platform.arch }}
      with:
        package-dir: .
        output-dir: dist
        config-file: pyproject.toml

    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*.whl

  check:
    name: All wheels built successfully
  
    if: always()

    needs:
    - build-wheels

    runs-on: Ubuntu-latest

    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
