name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2 019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BEFORE_ALL_LINUX: >
            curl -O https://dot.net/v1/dotnet-install.sh &&
            ls -lA &&
            chmod +x ./dotnet-install.sh &&
            ./dotnet-install.sh
          CIBW_BEFORE_ALL_MACOS: >
            curl -O https://dot.net/v1/dotnet-install.sh &&
            ls -lA &&
            chmod +x ./dotnet-install.sh &&
            ./dotnet-install.sh
          CIBW_BEFORE_ALL_WINDOWS: >
            curl -O https://dot.net/v1/dotnet-install.sh &&
            ./dotnet-install.sh
          CIBW_BEFORE_BUILD: >
            pip install toml GitPython &&
            python setup.py msbuild
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}"
        with:
          package-dir: .
          output-dir: dist
          config-file: pyproject.toml

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
