name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2 019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BEFORE_ALL: python setup.py vendor
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
        with:
          package-dir: .
          output-dir: dist
          config-file: pyproject.toml

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
