name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.pyver }} on ${{ matrix.platform.os }} ${{ matrix.platform.arch }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        pyver: [cp39, cp310, cp311, cp312]
        platform:
          - arch: arm64
            os: ubuntu-20.04
          - arch: auto64
            os: ubuntu-20.04
          - arch: arm64
            os: macos-10.15
          - arch: auto64
            os: macos-10.15
          - arch: i686
            os: windows-2019
          - arch: arm64
            os: windows-2019
          - arch: auto64
            os: windows-2019

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: ${{matrix.pyver}}-*
          CIBW_ARCHS: ${{ matrix.platform.arch }}
          CIBW_BEFORE_ALL_LINUX: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.416
          CIBW_ENVIRONMENT_LINUX: DOTNET_ROOT=$HOME/.dotnet PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}"
        with:
          package-dir: .
          output-dir: dist
          config-file: pyproject.toml

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
