name: Publish to TestPyPI

on: workflow_dispatch

jobs:
  pypi-publish:
    name: Publish package to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download build artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          path: dist
          name: artifact

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1 
        with:
          repository-url: https://test.pypi.org/legacy/
